server:
  port: 80

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        
spring:
  datasource: # DB설정
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://140.238.23.189:3306/MTDZ_LOG?characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 터널링 필요
    username: xpos
    password: dprtmvhtm0p9o8i
    ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
    
        
mtdz:
  json:
    url: https://data.metatoydragonz.io/meta