server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        
        
spring:
  application:
    name: mtdz-log
  datasource: # DB설정
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://140.238.23.189:3306/MTDZ_LOG?characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 터널링 필요
    username: xpos
    password: dprtmvhtm0p9o8i
    ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:sql-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
        
mtdz:
  json:
    url: https://data.metatoydragonz.io/meta
    
tomcat:
  ajp:
   protocol: AJP/1.3
   enabled: true
   port: 18080
   
---

spring:
  profiles: production 
 
logging:
  config: classpath:logback-production.xml