server:
  port: 8080

feign:
  client:
    config:
      KlaytnClient:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
        
        
spring:
  application:
    name: mtdz-log
  datasource: # DB설정
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://140.238.23.189:3306/MTDZ_LOG?characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 터널링 필요
    username: xpos
    password: dprtmvhtm0p9o8i
    ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  cache:
    type: redis
  redis:
    host: 140.238.23.189
    port: 6379
    password: mtdz7487

mybatis:
  mapper-locations: classpath:sql-mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
        
mtdz:
  contractAddress: '0x46DBdC7965CF3cd2257C054fEAb941a05Ff46488'
  json:
    url: https://data.metatoydragonz.io/meta

klaytn:
  api:
    host: https://th-api.klaytnapi.com
    x-chain-id: 8217
    accessKeyId: KASKW914TUX48DUA5ZR4PT1A
    secretAccessKey: BE_sQ07qwNOT6ju06zL9KYnpUwwwzKc1rs9r3BGv
    presets: 460
    
tomcat:
  ajp:
   protocol: AJP/1.3
   enabled: true
   port: 18080
    
pala:
  api:
    host: https://api.pala.world

bigdragon:
  api:
    host: https://coin.bigdragon.shop/api
    
bitThumb:
  api:
    host: https://api.bithumb.com
    
    
   
---

spring:
  profiles: production 
 
logging:
  config: classpath:logback-production.xml