server:
  port: 80

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        
mtdz:
  json:
    url: https://data.metatoydragonz.io/meta